### ISSUE TITLE
nbdime insists asking me to build it

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#15]
when I fire up jupyter-lab via `gadi_jupyter` I keep getting this message from `nbdime` asking to be build...

If I click "build" it fails; if I click "cancel" then it keeps asking me **every time**... 

<img width="1704" alt="Screen Shot 2020-04-21 at 12 15 02 pm" src="https://user-images.githubusercontent.com/7112768/79817885-cc736080-83c9-11ea-8473-9e7d9973e735.png">

Is this my fault? `gadi_jupyter`'s fault? something else?

**Comment by ScottWales** [comment]
I think its a central configuration issue. I've tried running `jupyter lab build` on the central install, can you check if thats fixed it for you?

**Comment by navidcy** [comment]
I haven't seen this message for a while so I presume/hope that what you did fixed it. I'm closing the issue... Thanks @ScottWales

**Comment by navidcy** [comment]
I got a scarier message today...
<img width="966" alt="Screen Shot 2020-04-28 at 10 31 09 pm" src="https://user-images.githubusercontent.com/7112768/80487435-22cf3900-89a0-11ea-9be8-93fd88c4d440.png">

**Comment by ScottWales** [comment]
There was an update to the conda environment yesterday evening. I've added the jupyter refresh command to the update script, should fix the issue.
