### ISSUE TITLE
`gadi_jupyter` hanging

### ISSUE THREAD

**Issue by edoddridge** [coecms/nci_scripts#17]
Thanks for a great script. It's extremely helpful.

Unfortunately, when I use the latest version of the `gadi_jupyter` script, my terminal hangs just after printing the `qsub` message.

If I revert to cb06b6ab87d27d6b969212168f76fa8117a305ae then everything works as expected.

**To reproduce the hang:**
- checkout origin/master
- modify options to add my username, project code, &c.
```
USER='ed7737'
PROJECT='ds0'
LOGINNODE='gadi.nci.org.au'
QUEUE='normal'
NCPUS='16'
MEM=''
WALLTIME=12:00:00
JOBFS=100gb
CONDA_ENV=analysis3-20.04
```
- run `./gadi_jupyter` locally
- See the following output from Gadi:
```
Starting notebook on gadi.nci.org.au...
qsub -N jupyter-notebook -P 'ds0' -q 'normal' -l 'ncpus=16,mem=64gb,walltime=12:00:00,jobfs=100gb'
```
- wait.
- continue waiting
- eventually trigger a keyboard interrupt and try something else.
- after interrupting, I get the following:
```
^CStopping queued job... (Ctrl-C will leave job in the queue)
Pseudo-terminal will not be allocated because stdin is not a terminal.
usage:
	qdel [-W force|suppress_email=X] [-x] job_identifier...
	qdel --version

```
I tried to see if anything had been submitted using the `uqstat` script. Nothing shows up.

**Alternatively, to make it work:**
- checkout cb06b6ab87d27d6b969212168f76fa8117a305ae
- modify defaults
- run `./gadi_jupyter`
- start sciencing in the Jupyter lab session that spawns.

**Comment by ScottWales** [comment]
The script will wait in that state until the job in the queue starts, which may take some time depending on the amount of people using Gadi, but that shouldn't be any longer than the previous version.

Did you run uqstat while the job was hanging, or after you had cancelled it? If the latter, you would need `uqstat -x` to see finished and deleted jobs.

If you cancel the job and then restart it quickly it is possible for the reconnect mechanism to get confused (the job is still listed in the queue for a minute while it gets cleaned up). Try deleting the contents of `/scratch/ds0/ed7737/tmp/runjp` to reset everything and retrying the new version of the script.

**Comment by edoddridge** [comment]
> The script will wait in that state until the job in the queue starts, which may take some time depending on the amount of people using Gadi, but that shouldn't be any longer than the previous version.

I left it for hours and nothing happened. When using the old version I find that Jupyter lab instance launches in minutes. 

> Did you run uqstat while the job was hanging, or after you had cancelled it? If the latter, you would need uqstat -x to see finished and deleted jobs.

While it was hanging (I also ran it afterwards to see if a job still existed but had become detached). In neither case did anything show up. This is why I think it wasn't submitting the job properly.

> If you cancel the job and then restart it quickly it is possible for the reconnect mechanism to get confused (the job is still listed in the queue for a minute while it gets cleaned up). Try deleting the contents of /scratch/ds0/ed7737/tmp/runjp to reset everything and retrying the new version of the script.

OK. I'll give that a go tomorrow.

**Comment by edoddridge** [comment]
Looks like there must have been something in the scratch folder that caused the hang. After deleting that, it's working today.

Thanks for your debugging help.
