### ISSUE TITLE
Reconnecting to gadi_jupyter on normalbw queue 

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#23]
I had a `gadi_jupyter` job submitted on `normalbw`. When restarted my computer and tried to reconnect the script seems to be stuck at 
```
(base) navid:nci_scripts/ (master✗) $ jupytergadi                                                                                                  [8:18:02]
Starting notebook on gadi.nci.org.au...
qsub -N jupyter-lab -P 'g40' -q 'normalbw' -l 'ncpus=28,mem=112gb,walltime=12:00:00,jobfs=100gb'
```
for ever...

**Comment by ScottWales** [comment]
Is there a job waiting or running in the queue?

**Comment by navidcy** [comment]
Yes,  there my job was still in the queue running at that time. Now I stopped it and submitted a new job.
Perhaps it was something temporary? I’ll let you know if this happens again...

**Comment by navidcy** [comment]
I'm closing this. It was probably something that occurred only that particular day. I have managed to reconnect to a `normalbw` job since then.
