### ISSUE TITLE
gadi_jupyter with gpu access

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#26]
I'd like to be able to open jupyter notebooks via `gadi_jupyter` with GPU access. E.g., something like:

```
qsub -q gpuvolta -P g40 -l walltime=8:00:00 -l ncpus=12 -l ngpus=1 -l mem=382GB
```

How could I, e.g., give the `ngpus` arg to `gadi_jupyter`?

**Comment by ScottWales** [comment]
`-g` now sets the number of gpus
