### ISSUE TITLE
`uqstat` and gpus

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#33]
Does `uqstat` take into account gpu usage in the calculated SUs?

**Comment by ScottWales** [comment]
I don't believe GPU usage is a factor for the SU cost - https://opus.nci.org.au/display/Help/Queue+Limits. Though I don't use the GPU queue myself, let me know if it's incorrect

**Comment by navidcy** [comment]
OK, I see. The cost only comes from the fact that you **need** to ask fro 12cpus per 1gpu requested. OK, never mind my comment then. I'm closing this!
