### ISSUE TITLE
add to default storage list with gadi_jupyter -s

### ISSUE THREAD

**Issue by aekiss** [coecms/nci_scripts#38]
Hi @ScottWales, is there are reason that `gadi_jupyter -s` replaces (rather than appends to) the list of storage?

I have access to a private NCI data path that isn't listed by `id -nG`, so I needed to modify `gadi_jupyter` to add the -s argument to the default storage list.

I'm wondering whether this would be preferable behaviour for other users?

**Comment by ScottWales** [comment]
It was added to account for cases when one of the storage systems was offline, so that projects could be removed if they were blocking the job from starting.

**Comment by aekiss** [comment]
Ah ok, sounds like it would be sensible to retain the existing behaviour then.
