### ISSUE TITLE
gadi_jupyter

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#5]
The gadi_jupyter.sh script should include a storage option, e.g., as @josuemtzmo implement it here:
https://github.com/josuemtzmo/cosima-cookbook/blob/5ed3861a7bb01dbf0b462381547ef375076e6562/scripts/jupyter_gadi.sh#L93

For the moment, I'm using @josuemtzmo's version to connect to gadi.

**Comment by ScottWales** [comment]
It asks for all storage areas you have access to - is that not working?

**Comment by navidcy** [comment]
OK, my bad sorry. I'm closing it.
