### ISSUE TITLE
gadi_jupyter.sh

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#7]
I run `gadi_jupyter.sh` with `-n 144` but I still **only** get a Dask with 48 cores when I do

```python
from dask.distributed import Client
client = Client()
client
```

<img width="374" alt="Screen Shot 2020-03-21 at 11 47 27 am" src="https://user-images.githubusercontent.com/7112768/77215708-cdfefe00-6b69-11ea-98b1-873c0357c67c.png">

How can I get more Dask workers?

**Comment by ScottWales** [comment]
Are you sure your problem will scale well to that many workers? It may be time to look beyond python.

The default dask cluster will use only one node, to use more you’ll need to look into something like the MPI spawner - check the dask distributed documentation for more info on this, I’ve not really used it.

On 21 Mar 2020, at 11:47 am, Navid C. Constantinou <notifications@github.com<mailto:notifications@github.com>> wrote:


I run gadi_jupyter.sh with -n 144 but I still only get a Dask with 48 cores when I do

from dask.distributed import Client
client = Client()
client

How can I get more Dask workers?

**Comment by navidcy** [comment]
Ok. Perhaps @ScottWales is right. I don’t really know whether my particular problem will scale well. 

I still think that one should be able to scale dask to any ncpus. But I’ll try to workaround something else for now.
